/*
 * Fast Counter
 *
 * A fast incrementing counter API
 *
 * API version: 1.0.0
 * Contact: daren@darenliang.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HitResponse struct {
	Key   string `bson:"key" json:"key"`
	Value int64  `bson:"value" json:"value"`
}
